### ISSUE TITLE
Support full set of HTTP verbs when calling serverless functions

### ISSUE THREAD

**Issue by pjindal91** [nhost/nhost-dart#55]
Based on the discussion [here](https://github.com/nhost/nhost-dart/pull/50#discussion_r795267235), it seems there might be a gap in functionality of the SDK or maybe support for GET/DELETE has been removed in new version of nhost. In case, it is supported, then would make sense to have support for GET/DELETE as well in addition to POST. It might even be a breaking change based on the design of the solution hence might make sense to put in the v2 release.

**Comment by shyndman** [comment]
I'm thinking that I'll default it to POST because many people won't care (they just want to call a function, doesn't matter how), and allow an override of the HTTP method for people who do.

That way we also get to stick to function terminology as well (ie `invoke`...although I might rename it `callFunction`)

**Comment by pjindal91** [comment]
I think that will do!

**Comment by shyndman** [comment]
Done, and a new set of beta packages have been published.

**Comment by pjindal91** [comment]
Thanks a lot @shyndman, looks great!
